``` {r}
#| label: load-imputed-pmm-forest
#| purl: true
#| eval: true
#| echo: false
#| output: false
load(file = paste(r_dir, "imputed_cart_model_forest.rds", sep = "/"))
load(file = paste(r_dir, "imputed_pmm_model_forest.rds", sep = "/"))
load(file = paste(r_dir, "imputed_rf_model_forest.rds", sep = "/"))

```


::: {.panel-tabset}

## PMM

``` {r}
#| label: fig-imputed-pmm-forest
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| out-width: "80%"
cowplot::plot_grid(imputed_pmm_model_forest[[1]]$importance_plot,
                   imputed_pmm_model_forest[[1]]$train_roc_curve_plot,
                   imputed_pmm_model_forest[[1]]$test_roc_curve_plot,
                   imputed_pmm_model_forest[[2]]$importance_plot,
                   imputed_pmm_model_forest[[2]]$train_roc_curve_plot,
                   imputed_pmm_model_forest[[2]]$test_roc_curve_plot,
                   imputed_pmm_model_forest[[3]]$importance_plot,
                   imputed_pmm_model_forest[[3]]$train_roc_curve_plot,
                   imputed_pmm_model_forest[[3]]$test_roc_curve_plot,
                   imputed_pmm_model_forest[[4]]$importance_plot,
                   imputed_pmm_model_forest[[4]]$train_roc_curve_plot,
                   imputed_pmm_model_forest[[4]]$test_roc_curve_plot,
                   imputed_pmm_model_forest[[5]]$importance_plot,
                   imputed_pmm_model_forest[[5]]$train_roc_curve_plot,
                   imputed_pmm_model_forest[[5]]$test_roc_curve_plot,
                   # labels = c("PMM", "Cart", "Random Forest"),
                   nrow = 5,
                   ncol = 3)

```

``` {r}
#| label: tab-imputed-pmm-forest-importance
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Importance of features from LASSO model of five PMM imputed datasets."
tidy_pmm_forest$importance |>
    knitr::kable(caption = "Importance of features from LASSO model of five PMM imputed datasets.")

```

``` {r}
#| label: tab-imputed-pmm-forest-train-metrics
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Classification metrics from LASSO model of five PMM imputed datasets (Training Data)."
tidy_pmm_forest$train_metrics |>
    knitr::kable(caption = "Classification metrics from LASSO model of five PMM imputed datasets (Training Data).",
                 digits = 4)

```

``` {r}
#| label: tab-imputed-pmm-forest-test-metrics
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Classification metrics from LASSO model of five PMM imputed datasets (Testing Data)."
tidy_pmm_forest$test_metrics |>
    knitr::kable(caption = "Classification metrics from LASSO model of five PMM imputed datasets (Testing Data).",
                 digits = 4)

```

## CART

``` {r}
#| label: fig-imputed-cart-forest
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| out-width: "80%"
cowplot::plot_grid(imputed_cart_model_forest[[1]]$importance_plot,
                   imputed_cart_model_forest[[1]]$train_roc_curve_plot,
                   imputed_cart_model_forest[[1]]$test_roc_curve_plot,
                   imputed_cart_model_forest[[2]]$importance_plot,
                   imputed_cart_model_forest[[2]]$train_roc_curve_plot,
                   imputed_cart_model_forest[[2]]$test_roc_curve_plot,
                   imputed_cart_model_forest[[3]]$importance_plot,
                   imputed_cart_model_forest[[3]]$train_roc_curve_plot,
                   imputed_cart_model_forest[[3]]$test_roc_curve_plot,
                   imputed_cart_model_forest[[4]]$importance_plot,
                   imputed_cart_model_forest[[4]]$train_roc_curve_plot,
                   imputed_cart_model_forest[[4]]$test_roc_curve_plot,
                   imputed_cart_model_forest[[5]]$importance_plot,
                   imputed_cart_model_forest[[5]]$train_roc_curve_plot,
                   imputed_cart_model_forest[[5]]$test_roc_curve_plot,
                   # labels = c("PMM", "Cart", "Random Forest"),
                   nrow = 5,
                   ncol = 3)

```

``` {r}
#| label: tab-imputed-cart-forest-importance
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Importance of features from LASSO model of five CART imputed datasets."
tidy_cart_forest$importance |>
    knitr::kable(caption = "Importance of features from LASSO model of five CART imputed datasets.")

```

``` {r}
#| label: tab-imputed-cart-forest-train-metrics
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Classification metrics from LASSO model of five CART imputed datasets (Training Data)."
tidy_cart_forest$train_metrics |>
    knitr::kable(caption = "Classification metrics from LASSO model of five CART imputed datasets (Training Data).",
                 digits = 4)

```

``` {r}
#| label: tab-imputed-cart-forest-test-metrics
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Classification metrics from LASSO model of five CART imputed datasets (Testing Data)."
tidy_cart_forest$test_metrics |>
    knitr::kable(caption = "Classification metrics from LASSO model of five CART imputed datasets (Testing Data).",
                 digits = 4)

```


## Random Forest

``` {r}
#| label: fig-imputed-rf-forest
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| out-width: "80%"
cowplot::plot_grid(imputed_rf_model_forest[[1]]$importance_plot,
                   imputed_rf_model_forest[[1]]$train_roc_curve_plot,
                   imputed_rf_model_forest[[1]]$test_roc_curve_plot,
                   imputed_rf_model_forest[[2]]$importance_plot,
                   imputed_rf_model_forest[[2]]$train_roc_curve_plot,
                   imputed_rf_model_forest[[2]]$test_roc_curve_plot,
                   imputed_rf_model_forest[[3]]$importance_plot,
                   imputed_rf_model_forest[[3]]$train_roc_curve_plot,
                   imputed_rf_model_forest[[3]]$test_roc_curve_plot,
                   imputed_rf_model_forest[[4]]$importance_plot,
                   imputed_rf_model_forest[[4]]$train_roc_curve_plot,
                   imputed_rf_model_forest[[4]]$test_roc_curve_plot,
                   imputed_rf_model_forest[[5]]$importance_plot,
                   imputed_rf_model_forest[[5]]$train_roc_curve_plot,
                   imputed_rf_model_forest[[5]]$test_roc_curve_plot,
                   # labels = c("PMM", "Rf", "Random Forest"),
                   nrow = 5,
                   ncol = 3)

```


``` {r}
#| label: tab-imputed-rf-forest-importance
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Importance of features from LASSO model of five RF imputed datasets."
tidy_rf_forest$importance |>
    knitr::kable(caption = "Importance of features from LASSO model of five RF imputed datasets.")

```

``` {r}
#| label: tab-imputed-rf-forest-train-metrics
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Classification metrics from LASSO model of five RF imputed datasets (Training Data)."
tidy_rf_forest$train_metrics |>
    knitr::kable(caption = "Classification metrics from LASSO model of five RF imputed datasets (Training Data).",
                 digits = 4)

```

``` {r}
#| label: tab-imputed-rf-forest-test-metrics
#| purl: true
#| eval: true
#| echo: false
#| output: true
#| tbl-caption: "Classification metrics from LASSO model of five RF imputed datasets (Testing Data)."
tidy_rf_forest$test_metrics |>
    knitr::kable(caption = "Classification metrics from LASSO model of five RF imputed datasets (Testing Data).",
                 digits = 4)

```

:::
